language: ruby
rvm:
  - 2.4.1
#sudo: false
cache: bundler
notifications:
  email: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
 - chmod +x script/cibuild
 
script: script/cibuild
  
after_success: s3_website push
