language: ruby
rvm:
- 2.4.1
sudo: false
notifications:
  email: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - master
before_install:
- chmod +x script/cibuild
before_script:
  - npm install firebase-tools -g
script: script/cibuild
after_success:
#  - s3_website push
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
