name: Mads Storm Hansen
title: Mads Storm Hansen
subtitle: Web developer
description: A web developer living in Copenhagen.
url: https://madsstorm.dk
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
