name: Mads Storm Hansen
title: Mads Storm Hansen
subtitle: Web developer
description: A web developer living in Copenhagen
url: https://madsstorm.dk
static-url: https://madsstorm.dk
permalink: /blog/:year/:month/:title/ # Trailing slash generates "folder + index.html" (For AWS S3 hosting)
tiles-source: posts # Accepts "posts" or "pages"
tiles-count: 10
github_url: https://github.com/madsstorm
twitter_url: https://twitter.com/madsstorm
linkedin_url: https://www.linkedin.com/in/madsstormhansen
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-assets
  - jekyll-git_metadata
  - jekyll-cloudinary
exclude:
  - vendor
  - Gemfile
  - rakefile
  - README.md
  - s3_website.yml
assets:
  sources:
    - _sass
    - assets
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
cloudinary:
  cloud_name: doedxrcnd
  only_prod: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      steps: 5
    tile:
      min_width: 320
      max_width: 960
      steps: 3