name: Mads Storm Hansen
title: Mads Storm Hansen
subtitle: Web developer
description: A web developer living in Copenhagen.
url: https://madsstorm.dk
static-url: https://heuristic-darwin-4479b2.netlify.com
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10
github_url: https://github.com/madsstorm
twitter_url: https://twitter.com/madsstorm
linkedin_url: https://www.linkedin.com/in/madsstormhansen
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
exclude:
  - Gemfile
include: ['_headers']
