[build]
  base = "src/"

[[redirects]]
  from = "http://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[redirects]]
  from = "https://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    Mads = "Nf. Storm"
