[build]
  base = "src"
  publish = "src/_site"

[[redirects]]
  from = "http://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[redirects]]
  from = "https://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://madsstormdk.report-uri.com/a/d/g"}],"include_subdomains":true},{"group":"csp-endpoint","max_age":31536000,"endpoints":[{"url":"https://madsstormdk.report-uri.com/r/d/csp/enforce"}],"include_subdomains":true}'
    X-XSS-Protection = "1; mode=block; report=https://madsstormdk.report-uri.com/r/d/xss/enforce"
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    Feature-Policy: "camera 'none'; display-capture 'none'; microphone 'none'; payment 'none"
    Content-Security-Policy = "block-all-mixed-content; upgrade-insecure-requests; default-src 'none'; base-uri 'none'; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com 'sha256-RoPTJAbXuu3oMWosRzhih74rvJ83yUE264L4I6Icf5s='; img-src 'self' data: https://res.cloudinary.com https://www.google-analytics.com https://www.googletagmanager.com; manifest-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; form-action 'none'; frame-ancestors 'none'; report-uri https://madsstormdk.report-uri.com/r/d/csp/enforce; report-to csp-endpoint"
    
