[build]
  base = "src"
  publish = "src/_site"

[[redirects]]
  from = "http://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[redirects]]
  from = "https://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*/"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Report-To = '{"group":"default","max_age":3600,"endpoints":[{"url":"https://report-api.madsstorm.dk/api/default"}],"include_subdomains":true},{"group":"csp-endpoint","max_age":3600,"endpoints":[{"url":"https://report-api.madsstorm.dk/api/csp"}],"include_subdomains":true}'
    X-XSS-Protection = "1; mode=block; report=https://report-api.madsstorm.dk/api/xss"
    NEL = '{"report_to":"default","max_age":3600,"include_subdomains":true}'
    Feature-Policy = "camera 'none'; microphone 'none'; payment 'none'"
    Content-Security-Policy = "block-all-mixed-content; upgrade-insecure-requests; default-src 'none'; base-uri 'none'; connect-src https://google-analytics.com https://www.google-analytics.com; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com https://ajax.cloudflare.com 'sha256-RoPTJAbXuu3oMWosRzhih74rvJ83yUE264L4I6Icf5s='; img-src 'self' data: https://res.cloudinary.com https://www.google-analytics.com https://www.googletagmanager.com; manifest-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; form-action 'none'; frame-ancestors 'none'; report-uri https://report-api.madsstorm.dk/api/csp; report-to csp-endpoint"
    
