[build]
  base = "src"
  publish = "src/_site"

[[redirects]]
  from = "http://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[redirects]]
  from = "https://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://madsstormdk.report-uri.com/a/d/g"}],"include_subdomains":true}'
