[build]
  base = "src"
  publish = "src/_site"

[[redirects]]
  from = "http://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[redirects]]
  from = "https://madsstorm-dk.netlify.com/*"
  to = "https://madsstorm.dk/:splat"
  force = true
  
[[headers]]
  for = "/*"
  [headers.values]
    Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://madsstormdk.report-uri.com/a/d/g"}],"include_subdomains":true}'
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block; report=https://madsstormdk.report-uri.com/r/d/xss/enforce"
    Referrer-Policy = "no-referrer"   
    Content-Security-Policy-Report-Only = "default-src 'none'; script-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://madsstormdk.report-uri.com/r/d/csp/wizard"
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
